language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
#    - android-23
#    - android-26
#    - android-17
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
jdk:
  - oraclejdk8


before_install: echo "before_install"
install: echo "install"
before_script: echo "before_script"
script:
  - echo "build the script"
  #使用--project-prop或者-P都可以传参
  - ./gradlew assemble -PBINTRAY_USER=$BINTRAY_USER --project-prop BINTRAY_APIKEY=$BINTRAY_APIKEY

after_success:
  - echo "after_success"
  - ./script/push_jfrog_maven.sh `pwd` $BINTRAY_USER $BINTRAY_APIKEY

after_failure:
  - echo "after_failure"
before_deploy:
  - echo "before_deploy"
deploy:
  provider: script
  script: echo "deploy..."

after_deploy:
  - echo "after_deploy"

after_script:
  - echo "after_script"

before_cache:
  - echo "before_cache"
#cache:
#  - echo "cache"

#os: osx
#git:

#you can safelist them all with regular expressions, for example /^v\d+\.\d+(\.\d+)?(-\S*)?$/
# blocklist
#branches:
#  except:
#  - legacy
#  - experimental
#
## safelist
#branches:
#  only:
#  - master
#  - stable

sudo: required

services:
- docker

